// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Vehicle4_System","status":true,"description":"[V.2.6 Reboard Fixed] Vehicle4 Custom System - Stable Reboard, Animated Board/Dismount, Auto Spawn Friendly","parameters":{"--- Pengaturan Visual ---":"","Vehicle Image":"Vehicle","Vehicle Index":"0","--- Pengaturan Sistem ---":"","Speed":"5","Encounter Rate":"0","Disable Dash":"true","--- Pengaturan Boarding ---":"","Board Rule":"adjacentOrOn","Animation Mode":"default","Fade Duration":"18","--- Pengaturan Spawn Otomatis ---":"","Auto Spawn":"true","Spawn Map ID":"2","Spawn X":"18","Spawn Y":"23","--- Pengaturan Passability ---":"","Passability Type":"land","--- Pengaturan Audio ---":"","BGM Name":"","BGM Volume":"90","BGM Pitch":"100","SE Get On":"","SE Get On Volume":"90","SE Get Off":"","SE Get Off Volume":"90"}}
];
