// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Vehicle4_System","status":true,"description":"[V.1.5 Compact] Vehicle4 Custom System - Stable, Shorter Version","parameters":{"--- Pengaturan Visual ---":"","Vehicle Image":"KeretaApi","Vehicle Index":"0","--- Pengaturan Sistem ---":"","Speed":"4","Encounter Rate":"0","Disable Dash":"true","--- Pengaturan Boarding ---":"","Board Rule":"frontOrOn","Animation Mode":"default","Fade Duration":"18","--- Pengaturan Spawn Otomatis ---":"","Auto Spawn":"true","Spawn Map ID":"2","Spawn X":"18","Spawn Y":"23","--- Pengaturan Passability ---":"","Passability Type":"land","--- Pengaturan Audio ---":"","BGM Name":"","BGM Volume":"90","BGM Pitch":"100","SE Get On":"","SE Get On Volume":"90","SE Get Off":"","SE Get Off Volume":"90"}}
];
